//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class wgs047
    {
        public long cur001 { get; set; }
        public System.DateTime cur002 { get; set; }
        public int cur003 { get; set; }
        public int cur004 { get; set; }
        public int cur005 { get; set; }
        public string cur006 { get; set; }
        public string cur007 { get; set; }
        public int cur008 { get; set; }
        public int cur009 { get; set; }
        public string cur010 { get; set; }
        public string cur011 { get; set; }
        public int cur012 { get; set; }
        public decimal cur013 { get; set; }
        public decimal cur014 { get; set; }
        public decimal cur015 { get; set; }
        public decimal cur016 { get; set; }
        public decimal cur017 { get; set; }
        public decimal cur018 { get; set; }
        public System.DateTime cur019 { get; set; }
        public System.DateTime cur020 { get; set; }
        public System.DateTime cur021 { get; set; }
        public byte cur022 { get; set; }
        public decimal cur023 { get; set; }
        public decimal cur024 { get; set; }
        public decimal cur025 { get; set; }
    }
}
