//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class wgs010
    {
        public int sb001 { get; set; }
        public string sb002 { get; set; }
        public string sb003 { get; set; }
        public string sb004 { get; set; }
        public string sb005 { get; set; }
        public string sb006 { get; set; }
        public int sb007 { get; set; }
        public int sb008 { get; set; }
        public decimal sb009 { get; set; }
    }
}
