//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class wgs016
    {
        public int mu001 { get; set; }
        public string mu002 { get; set; }
        public string mu003 { get; set; }
        public string mu004 { get; set; }
        public string mu005 { get; set; }
        public int mu006 { get; set; }
        public int pg001 { get; set; }
    }
}
