//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class wgs043
    {
        public long tf001 { get; set; }
        public int tf002 { get; set; }
        public string tf003 { get; set; }
        public string tf004 { get; set; }
        public int tf005 { get; set; }
        public string tf006 { get; set; }
        public string tf007 { get; set; }
        public decimal tf008 { get; set; }
        public System.DateTime tf009 { get; set; }
        public string tf010 { get; set; }
        public long tf011 { get; set; }
        public byte tf012 { get; set; }
        public string tf013 { get; set; }
        public Nullable<System.DateTime> tf014 { get; set; }
        public decimal tf015 { get; set; }
        public int mu001 { get; set; }
        public string mu002 { get; set; }
    }
}
