//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class wgs055
    {
        public int f001 { get; set; }
        public int u001 { get; set; }
        public string u002 { get; set; }
        public double f002 { get; set; }
        public int f003 { get; set; }
        public System.DateTime f004 { get; set; }
        public int f005 { get; set; }
        public System.DateTime f006 { get; set; }
        public System.DateTime f007 { get; set; }
        public System.DateTime f008 { get; set; }
        public int f009 { get; set; }
    }
}
