//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class wgs015
    {
        public int pg001 { get; set; }
        public int pg002 { get; set; }
        public string pg003 { get; set; }
        public string pg004 { get; set; }
        public string pg005 { get; set; }
    }
}
