//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class wgs025
    {
        public int onl001 { get; set; }
        public int u001 { get; set; }
        public string u002 { get; set; }
        public string u003 { get; set; }
        public string onl002 { get; set; }
        public System.DateTime onl003 { get; set; }
        public System.DateTime onl004 { get; set; }
        public string onl005 { get; set; }
        public int onl006 { get; set; }
        public string onl007 { get; set; }
        public string onl008 { get; set; }
        public string onl009 { get; set; }
        public string onl010 { get; set; }
    }
}
