//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class wgs004
    {
        public int sm001 { get; set; }
        public int sm002 { get; set; }
        public string sm003 { get; set; }
        public string sm004 { get; set; }
        public int sm005 { get; set; }
        public string sm006 { get; set; }
        public string sm007 { get; set; }
        public string sm008 { get; set; }
        public int sm009 { get; set; }
        public int sm010 { get; set; }
        public int sm011 { get; set; }
        public decimal sm012 { get; set; }
        public byte sm013 { get; set; }
        public byte sm014 { get; set; }
    }
}
