//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class wgs039
    {
        public int sr001 { get; set; }
        public int u001 { get; set; }
        public int r001 { get; set; }
        public int sr002 { get; set; }
        public decimal sr003 { get; set; }
        public int sr004 { get; set; }
        public string sr005 { get; set; }
        public string sr006 { get; set; }
        public string sr007 { get; set; }
        public decimal sr008 { get; set; }
        public string sr009 { get; set; }
        public string sr010 { get; set; }
        public string sr011 { get; set; }
        public string sr012 { get; set; }
        public string sr013 { get; set; }
        public decimal sr014 { get; set; }
        public string sr015 { get; set; }
        public string sr016 { get; set; }
        public string sr017 { get; set; }
        public decimal sr018 { get; set; }
    }
}
