//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class wgs005
    {
        public int gs001 { get; set; }
        public int g001 { get; set; }
        public int gc001 { get; set; }
        public string gs002 { get; set; }
        public System.DateTime gs003 { get; set; }
        public System.DateTime gs004 { get; set; }
        public System.DateTime gs005 { get; set; }
        public System.DateTime gs006 { get; set; }
        public string gs007 { get; set; }
        public byte gs008 { get; set; }
        public byte gs009 { get; set; }
        public byte gs010 { get; set; }
        public byte gs011 { get; set; }
    }
}
