//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class wgs051
    {
        public long us001 { get; set; }
        public int us002 { get; set; }
        public string us003 { get; set; }
        public string us004 { get; set; }
        public int us005 { get; set; }
        public string us006 { get; set; }
        public string us007 { get; set; }
        public decimal us008 { get; set; }
        public decimal us009 { get; set; }
        public System.DateTime us010 { get; set; }
        public System.DateTime us011 { get; set; }
        public System.DateTime us012 { get; set; }
        public decimal us013 { get; set; }
        public int us014 { get; set; }
        public int us015 { get; set; }
        public decimal us016 { get; set; }
    }
}
