//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class wgs028
    {
        public int gtp001 { get; set; }
        public string gtp002 { get; set; }
        public string gtp003 { get; set; }
        public decimal gtp004 { get; set; }
        public decimal gtp005 { get; set; }
        public decimal gtp006 { get; set; }
        public decimal gtp007 { get; set; }
        public int gtp008 { get; set; }
        public decimal gtp009 { get; set; }
        public string gtp010 { get; set; }
        public int gtp011 { get; set; }
        public decimal gtp012 { get; set; }
        public int u001 { get; set; }
        public int gc001 { get; set; }
        public int g001 { get; set; }
        public int gp001 { get; set; }
        public int gm001 { get; set; }
        public int gm002 { get; set; }
    }
}
