//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class wgs034
    {
        public long ubp001 { get; set; }
        public decimal ubp002 { get; set; }
        public decimal ubp003 { get; set; }
        public long so001 { get; set; }
        public int u001 { get; set; }
        public string u002 { get; set; }
        public string u003 { get; set; }
        public int gc001 { get; set; }
        public int g001 { get; set; }
        public int gm001 { get; set; }
        public int gm002 { get; set; }
    }
}
