//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class wgs042
    {
        public long dr001 { get; set; }
        public System.DateTime dr002 { get; set; }
        public System.DateTime dr003 { get; set; }
        public decimal dr004 { get; set; }
        public decimal dr005 { get; set; }
        public decimal dr006 { get; set; }
        public decimal dr007 { get; set; }
        public decimal dr008 { get; set; }
        public decimal dr009 { get; set; }
        public decimal dr010 { get; set; }
        public decimal dr011 { get; set; }
        public decimal dr012 { get; set; }
        public decimal dr013 { get; set; }
        public decimal dr014 { get; set; }
        public decimal dr015 { get; set; }
        public decimal dr016 { get; set; }
        public decimal dr017 { get; set; }
        public decimal dr018 { get; set; }
        public int u001 { get; set; }
        public string u002 { get; set; }
        public string u003 { get; set; }
        public Nullable<decimal> dr019 { get; set; }
        public Nullable<decimal> dr020 { get; set; }
    }
}
