//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class wgs049
    {
        public int u001 { get; set; }
        public string u002 { get; set; }
        public string u003 { get; set; }
        public string u004 { get; set; }
        public System.DateTime u005 { get; set; }
        public Nullable<System.DateTime> u006 { get; set; }
        public Nullable<System.DateTime> u007 { get; set; }
        public byte u008 { get; set; }
        public string u009 { get; set; }
        public string u010 { get; set; }
        public string u011 { get; set; }
        public int u012 { get; set; }
        public int u013 { get; set; }
        public string u014 { get; set; }
        public int u015 { get; set; }
        public int u016 { get; set; }
        public string u017 { get; set; }
        public int u018 { get; set; }
        public decimal u019 { get; set; }
        public int u020 { get; set; }
        public string u021 { get; set; }
        public string u022 { get; set; }
        public int u023 { get; set; }
        public double u024 { get; set; }
    }
}
