//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class wgs008
    {
        public int gpd001 { get; set; }
        public int gc001 { get; set; }
        public int gp001 { get; set; }
        public int gm001 { get; set; }
        public int gm002 { get; set; }
        public decimal gpd002 { get; set; }
        public decimal gpd003 { get; set; }
        public decimal gpd004 { get; set; }
        public decimal gpd005 { get; set; }
        public decimal gpd006 { get; set; }
        public decimal gpd007 { get; set; }
        public decimal gpd008 { get; set; }
        public decimal gpd009 { get; set; }
    }
}
