//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class wgs020
    {
        public long uw001 { get; set; }
        public int u001 { get; set; }
        public string u002 { get; set; }
        public string u003 { get; set; }
        public int uwi001 { get; set; }
        public decimal uw002 { get; set; }
        public decimal uw003 { get; set; }
        public System.DateTime uw004 { get; set; }
        public Nullable<System.DateTime> uw005 { get; set; }
        public int uw006 { get; set; }
        public string uw007 { get; set; }
        public string uw008 { get; set; }
        public string uw009 { get; set; }
        public string uw010 { get; set; }
        public string uw011 { get; set; }
        public string uw012 { get; set; }
        public string uw013 { get; set; }
        public string uw014 { get; set; }
        public string uw015 { get; set; }
        public decimal uw016 { get; set; }
        public string uw017 { get; set; }
        public int mu001 { get; set; }
        public string mu002 { get; set; }
        public int uw018 { get; set; }
    }
}
