//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class wgs011
    {
        public System.Guid log001 { get; set; }
        public int u001 { get; set; }
        public string u002 { get; set; }
        public string u003 { get; set; }
        public Nullable<int> sm001 { get; set; }
        public Nullable<int> sm002 { get; set; }
        public Nullable<int> sm005 { get; set; }
        public string log002 { get; set; }
        public string log003 { get; set; }
        public System.DateTime log004 { get; set; }
        public string log005 { get; set; }
        public int log006 { get; set; }
        public string log007 { get; set; }
        public string log008 { get; set; }
        public string log009 { get; set; }
        public string log010 { get; set; }
        public int log011 { get; set; }
        public string log012 { get; set; }
        public string log013 { get; set; }
        public string log014 { get; set; }
    }
}
