//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class wgs053
    {
        public long tpi001 { get; set; }
        public int tpi002 { get; set; }
        public string tpi003 { get; set; }
        public string tpi004 { get; set; }
        public string tpi005 { get; set; }
        public decimal tpi006 { get; set; }
        public decimal tpi007 { get; set; }
        public decimal tpi008 { get; set; }
        public System.DateTime tpi009 { get; set; }
        public int gm001 { get; set; }
        public int gm002 { get; set; }
        public long so001 { get; set; }
        public int g001 { get; set; }
        public string gs002 { get; set; }
    }
}
