//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class wgs044
    {
        public long msg001 { get; set; }
        public string msg002 { get; set; }
        public string msg003 { get; set; }
        public int msg004 { get; set; }
        public int msg005 { get; set; }
        public System.DateTime msg006 { get; set; }
        public byte msg007 { get; set; }
        public string msg008 { get; set; }
        public string msg009 { get; set; }
        public string msg010 { get; set; }
        public string msg011 { get; set; }
        public byte msg012 { get; set; }
        public byte msg013 { get; set; }
    }
}
