//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class wgs035
    {
        public long ar001 { get; set; }
        public string ar002 { get; set; }
        public string ar003 { get; set; }
        public Nullable<System.DateTime> ar004 { get; set; }
        public byte ar005 { get; set; }
        public byte ar006 { get; set; }
        public int ar007 { get; set; }
        public int ar008 { get; set; }
        public byte ar009 { get; set; }
        public byte ar010 { get; set; }
        public int u001 { get; set; }
        public string u002 { get; set; }
        public string u003 { get; set; }
    }
}
