//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class wgs033
    {
        public int r001 { get; set; }
        public string r002 { get; set; }
        public decimal r003 { get; set; }
        public int r004 { get; set; }
        public int r005 { get; set; }
        public string r006 { get; set; }
        public System.DateTime r007 { get; set; }
        public int rc001 { get; set; }
        public Nullable<int> r008 { get; set; }
        public int r009 { get; set; }
        public System.DateTime r010 { get; set; }
        public int r011 { get; set; }
    }
}
