//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class wgs024
    {
        public int uwt001 { get; set; }
        public string uwt002 { get; set; }
        public string uwt003 { get; set; }
        public int uwt004 { get; set; }
        public string uwt005 { get; set; }
        public decimal uwt006 { get; set; }
    }
}
