//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class wgs009
    {
        public int ct001 { get; set; }
        public int sb001 { get; set; }
        public string ct002 { get; set; }
        public string ct003 { get; set; }
        public string ct004 { get; set; }
        public string ct005 { get; set; }
        public string ct006 { get; set; }
        public string ct007 { get; set; }
        public string ct008 { get; set; }
        public string ct009 { get; set; }
        public string ct010 { get; set; }
        public string ct011 { get; set; }
        public int ct012 { get; set; }
    }
}
