//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class wgs027
    {
        public string cfg001 { get; set; }
        public string cfg002 { get; set; }
        public string cfg003 { get; set; }
        public string cfg004 { get; set; }
        public string cfg005 { get; set; }
        public string cfg006 { get; set; }
        public decimal cfg007 { get; set; }
    }
}
