//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class wgs026
    {
        public int ulg001 { get; set; }
        public int u001 { get; set; }
        public string u002 { get; set; }
        public string u003 { get; set; }
        public System.DateTime ulg002 { get; set; }
        public Nullable<System.DateTime> ulg003 { get; set; }
        public string ulg004 { get; set; }
        public int ulg005 { get; set; }
        public int ulg006 { get; set; }
        public int ulg007 { get; set; }
        public string ulg008 { get; set; }
    }
}
