//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class wgs002
    {
        public int gm001 { get; set; }
        public int gm002 { get; set; }
        public int g001 { get; set; }
        public int gmg001 { get; set; }
        public string gm003 { get; set; }
        public string gm004 { get; set; }
        public string gm005 { get; set; }
        public string gm006 { get; set; }
        public string gm007 { get; set; }
        public string gm008 { get; set; }
        public string gm009 { get; set; }
        public string gm010 { get; set; }
        public string gm011 { get; set; }
        public string gm012 { get; set; }
        public Nullable<decimal> gm013 { get; set; }
    }
}
