//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class wgs013
    {
        public int ur001 { get; set; }
        public int u001 { get; set; }
        public int u002 { get; set; }
        public string u001n { get; set; }
        public string u001nn { get; set; }
        public string u002n { get; set; }
        public string u002nn { get; set; }
        public int u001l { get; set; }
        public int u002l { get; set; }
    }
}
