//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class wgs045
    {
        public long so001 { get; set; }
        public int u001 { get; set; }
        public string u002 { get; set; }
        public string u003 { get; set; }
        public int g001 { get; set; }
        public int gc001 { get; set; }
        public int gm001 { get; set; }
        public int gm002 { get; set; }
        public int gpd001 { get; set; }
        public int up001 { get; set; }
        public int mu001 { get; set; }
        public string mu002 { get; set; }
        public long sto001 { get; set; }
        public int gs001 { get; set; }
        public string gs002 { get; set; }
        public string so002 { get; set; }
        public int so003 { get; set; }
        public decimal so004 { get; set; }
        public int so005 { get; set; }
        public byte so006 { get; set; }
        public System.DateTime so007 { get; set; }
        public Nullable<System.DateTime> so008 { get; set; }
        public byte so009 { get; set; }
        public decimal so010 { get; set; }
        public decimal so011 { get; set; }
        public string so012 { get; set; }
        public decimal so013 { get; set; }
        public string so014 { get; set; }
        public string so015 { get; set; }
        public byte so016 { get; set; }
        public byte so017 { get; set; }
        public decimal so018 { get; set; }
        public string so019 { get; set; }
        public string so020 { get; set; }
        public byte so021 { get; set; }
        public byte so022 { get; set; }
        public byte so023 { get; set; }
        public string so024 { get; set; }
        public byte so025 { get; set; }
        public decimal so026 { get; set; }
        public decimal so027 { get; set; }
        public long so028 { get; set; }
        public string so029 { get; set; }
        public string so030 { get; set; }
        public string so031 { get; set; }
        public string so032 { get; set; }
        public Nullable<bool> so033 { get; set; }
    }
}
