//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class wgs052
    {
        public int u001 { get; set; }
        public decimal uf001 { get; set; }
        public decimal uf002 { get; set; }
        public decimal uf003 { get; set; }
        public decimal uf004 { get; set; }
        public decimal uf005 { get; set; }
        public decimal uf006 { get; set; }
        public decimal uf007 { get; set; }
        public byte uf008 { get; set; }
        public Nullable<System.DateTime> uf009 { get; set; }
        public Nullable<System.DateTime> uf010 { get; set; }
        public Nullable<System.DateTime> uf011 { get; set; }
        public decimal uf012 { get; set; }
        public decimal uf013 { get; set; }
        public decimal uf014 { get; set; }
    }
}
