//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class wgs007
    {
        public int gp001 { get; set; }
        public int gc001 { get; set; }
        public string gp002 { get; set; }
        public string gp003 { get; set; }
        public int gp004 { get; set; }
        public int gp005 { get; set; }
        public int gp006 { get; set; }
        public decimal gp007 { get; set; }
        public decimal gp008 { get; set; }
        public decimal gp009 { get; set; }
    }
}
