//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class wgs017
    {
        public int up001 { get; set; }
        public int u001 { get; set; }
        public int u012 { get; set; }
        public Nullable<int> gp001 { get; set; }
        public int gc001 { get; set; }
        public int g001 { get; set; }
        public decimal up002 { get; set; }
        public decimal up003 { get; set; }
        public decimal up004 { get; set; }
        public decimal up005 { get; set; }
        public int up006 { get; set; }
        public decimal up007 { get; set; }
        public decimal up008 { get; set; }
        public decimal up009 { get; set; }
        public decimal up010 { get; set; }
        public decimal up011 { get; set; }
        public decimal up012 { get; set; }
        public decimal up013 { get; set; }
        public string up014 { get; set; }
        public string up015 { get; set; }
        public string up016 { get; set; }
        public string up017 { get; set; }
        public string up018 { get; set; }
    }
}
