//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class wgs001
    {
        public int g001 { get; set; }
        public string g002 { get; set; }
        public string g003 { get; set; }
        public string g004 { get; set; }
        public string g005 { get; set; }
        public string g006 { get; set; }
        public string g007 { get; set; }
        public string g008 { get; set; }
        public decimal g009 { get; set; }
        public Nullable<bool> g010 { get; set; }
    }
}
