//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class wgs057
    {
        public int c001 { get; set; }
        public string u001 { get; set; }
        public string u002 { get; set; }
        public string u003 { get; set; }
        public string u004 { get; set; }
        public decimal cm001 { get; set; }
        public decimal cm002 { get; set; }
        public decimal cm003 { get; set; }
        public decimal cm004 { get; set; }
        public decimal cm005 { get; set; }
        public decimal cm006 { get; set; }
        public decimal cm007 { get; set; }
        public decimal cm008 { get; set; }
        public decimal cm009 { get; set; }
        public decimal c002 { get; set; }
        public decimal c003 { get; set; }
        public System.DateTime c004 { get; set; }
        public string c005 { get; set; }
        public string c006 { get; set; }
        public Nullable<bool> c007 { get; set; }
    }
}
