//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class wgs018
    {
        public int u001 { get; set; }
        public string ue001 { get; set; }
        public string ue002 { get; set; }
        public string ue003 { get; set; }
        public string ue004 { get; set; }
        public string ue005 { get; set; }
        public string ue006 { get; set; }
        public string ue007 { get; set; }
        public string ue008 { get; set; }
        public string ue009 { get; set; }
        public string ue010 { get; set; }
        public string ue011 { get; set; }
        public string ue012 { get; set; }
        public string ue013 { get; set; }
        public string ue014 { get; set; }
        public string ue015 { get; set; }
    }
}
