//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class wgs023
    {
        public int uwi001 { get; set; }
        public int u001 { get; set; }
        public int uwt001 { get; set; }
        public string uwi002 { get; set; }
        public string uwi003 { get; set; }
        public string uwi004 { get; set; }
        public string uwi005 { get; set; }
        public string uwi006 { get; set; }
        public string uwi007 { get; set; }
        public string uwi008 { get; set; }
        public string uwi009 { get; set; }
        public Nullable<System.DateTime> uwi010 { get; set; }
    }
}
