//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class wgs031
    {
        public long sco001 { get; set; }
        public int u001 { get; set; }
        public string u002 { get; set; }
        public string u003 { get; set; }
        public int gc001 { get; set; }
        public int g001 { get; set; }
        public int gm001 { get; set; }
        public int gm002 { get; set; }
        public long sto001 { get; set; }
        public string sco002 { get; set; }
        public int sco003 { get; set; }
        public int gs001 { get; set; }
        public string gs002 { get; set; }
        public Nullable<System.DateTime> gs003 { get; set; }
        public Nullable<System.DateTime> gs004 { get; set; }
        public string gs007 { get; set; }
        public long so001 { get; set; }
        public decimal sco004 { get; set; }
        public decimal sco005 { get; set; }
        public decimal sco006 { get; set; }
        public decimal sco007 { get; set; }
        public decimal sco008 { get; set; }
        public byte sco009 { get; set; }
        public string sco010 { get; set; }
        public int sco011 { get; set; }
        public int sco012 { get; set; }
        public string sco013 { get; set; }
        public string sco014 { get; set; }
        public string sco015 { get; set; }
        public int sco016 { get; set; }
        public System.DateTime sco017 { get; set; }
        public byte sco018 { get; set; }
        public int sco019 { get; set; }
    }
}
