//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class wgs056
    {
        public int s001 { get; set; }
        public decimal s002 { get; set; }
        public Nullable<double> s003 { get; set; }
        public int s004 { get; set; }
        public int s005 { get; set; }
        public int u001 { get; set; }
        public string u002 { get; set; }
        public double f002 { get; set; }
        public System.DateTime s006 { get; set; }
        public System.DateTime s007 { get; set; }
        public string s008 { get; set; }
        public System.DateTime s009 { get; set; }
        public string s010 { get; set; }
        public System.DateTime s011 { get; set; }
        public decimal s012 { get; set; }
        public decimal s013 { get; set; }
        public decimal s014 { get; set; }
        public decimal s015 { get; set; }
        public Nullable<decimal> s016 { get; set; }
    }
}
