//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class wgs021
    {
        public long uxf001 { get; set; }
        public int u001 { get; set; }
        public string u002 { get; set; }
        public string u003 { get; set; }
        public int g001 { get; set; }
        public int gc001 { get; set; }
        public int gm001 { get; set; }
        public int gm002 { get; set; }
        public long so001 { get; set; }
        public string gs002 { get; set; }
        public long uc001 { get; set; }
        public long tf001 { get; set; }
        public long uw001 { get; set; }
        public decimal uxf002 { get; set; }
        public decimal uxf003 { get; set; }
        public decimal uxf004 { get; set; }
        public decimal uxf005 { get; set; }
        public decimal uxf006 { get; set; }
        public decimal uxf007 { get; set; }
        public decimal uxf008 { get; set; }
        public decimal uxf009 { get; set; }
        public decimal uxf010 { get; set; }
        public decimal uxf011 { get; set; }
        public decimal uxf012 { get; set; }
        public decimal uxf013 { get; set; }
        public System.DateTime uxf014 { get; set; }
        public string uxf015 { get; set; }
        public byte uxf016 { get; set; }
        public string uxf017 { get; set; }
        public decimal uxf018 { get; set; }
        public decimal uxf019 { get; set; }
    }
}
