//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class wgs041
    {
        public int nc001 { get; set; }
        public string nc002 { get; set; }
        public string nc003 { get; set; }
        public System.DateTime nc004 { get; set; }
        public decimal nc005 { get; set; }
        public byte nc006 { get; set; }
        public int nc007 { get; set; }
        public string nc008 { get; set; }
        public byte nc009 { get; set; }
    }
}
