//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class wgs019
    {
        public long uc001 { get; set; }
        public int u001 { get; set; }
        public string u002 { get; set; }
        public string u003 { get; set; }
        public decimal uc002 { get; set; }
        public decimal uc003 { get; set; }
        public decimal uc004 { get; set; }
        public string uc005 { get; set; }
        public Nullable<System.DateTime> uc006 { get; set; }
        public Nullable<System.DateTime> uc007 { get; set; }
        public int uc008 { get; set; }
        public string uc009 { get; set; }
        public string uc010 { get; set; }
        public string uc011 { get; set; }
        public string uc012 { get; set; }
        public decimal uc013 { get; set; }
        public byte uc014 { get; set; }
        public int sb001 { get; set; }
        public int ct001 { get; set; }
        public int mu001 { get; set; }
        public string mu002 { get; set; }
        public int mu001x { get; set; }
        public string mu002x { get; set; }
    }
}
