//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class wgs030
    {
        public long sto001 { get; set; }
        public int u001 { get; set; }
        public string u002 { get; set; }
        public string u003 { get; set; }
        public int gc001 { get; set; }
        public int g001 { get; set; }
        public decimal sto002 { get; set; }
        public string sto003 { get; set; }
        public System.DateTime sto004 { get; set; }
        public byte sto005 { get; set; }
        public string sto006 { get; set; }
        public decimal sto007 { get; set; }
        public decimal sto008 { get; set; }
        public byte sto009 { get; set; }
        public string sto010 { get; set; }
        public int sto011 { get; set; }
        public string sto012 { get; set; }
        public int sto013 { get; set; }
    }
}
